services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      -  "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:17
    container_name: furniweb-db
    restart: always
    environment:
      POSTGRES_DB: furniweb
      POSTGRES_USER: furniuser
      POSTGRES_PASSWORD: furnipass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
