# Generated by Django 5.2.9 on 2025-12-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_product_buy_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="vendor",
        ),
        migrations.AddField(
            model_name="product",
            name="vendername",
            field=models.CharField(
                default="default_vendor", max_length=200, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="Vendor",
        ),
    ]
