# Generated by Django 5.2.9 on 2025-12-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_item_delete_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="user",
        ),
    ]
