# Generated by Django 5.2.9 on 2025-12-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
